In [1]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import numpy as np
import time

In [2]:
x,y=load_diabetes(return_X_y=True)

In [3]:
print(x.shape)

(442, 10)


In [4]:
y.shape

(442,)

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [6]:
x_train.shape

(353, 10)

In [7]:
reg=LinearRegression()

In [8]:
reg.fit(x_train,y_train)

LinearRegression()

In [9]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [10]:
y_pred=reg.predict(x_test)

In [11]:
r2_score(y_test,y_pred)

0.4399338661568968

In [15]:
class MBGDregressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.intercept_=None
        self.coef_=None
        self.lr=learning_rate
        self.epochs=epochs
        self.batch_size=batch_size
    
    def fit(self,x_train,y_train):
        #init my coefficients
        self.intercept_=0
        self.coef_=np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(x_train.shape[0]/self.batch_size)):
                idx=random.sample(range(x_train.shape[0]),self.batch_size)
                
                y_hat= np.dot(x_train[idx],self.coef_)+self.intercept_
                
                intercept_der= -2*np.mean(y_train[idx]-y_hat)
                
                self.intercept_=self.intercept_-(self.lr*intercept_der)
                
                coef_der= -2 * np.dot((y_train[idx]-y_hat),x_train[idx])
                self.coef_=self.coef_-(self.lr*coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) +self.intercept_

In [16]:
import random
random.sample(range(1,100),10)

[32, 55, 13, 52, 20, 41, 96, 81, 79, 24]

In [17]:
x_train[[53, 89, 90, 16, 59, 41, 80, 43, 79, 69]]

array([[ 0.02717829, -0.04464164, -0.00728377, -0.05042748,  0.0754844 ,
         0.05661859,  0.03391355, -0.00259226,  0.04344397,  0.01549073],
       [-0.07090025, -0.04464164, -0.00405033, -0.04009893, -0.06623874,
        -0.07866155,  0.05232174, -0.0763945 , -0.05140387, -0.03421455],
       [ 0.00538306,  0.05068012,  0.03043966,  0.0838437 , -0.03734373,
        -0.0473467 ,  0.01550536, -0.03949338,  0.0086406 ,  0.01549073],
       [ 0.07076875,  0.05068012,  0.01211685,  0.0563009 ,  0.03420581,
         0.04941617, -0.03971921,  0.03430886,  0.02736405, -0.0010777 ],
       [-0.00914709, -0.04464164, -0.06225218, -0.07452744, -0.02358421,
        -0.01321352,  0.00446045, -0.03949338, -0.03581619, -0.04664087],
       [-0.00188202,  0.05068012, -0.02452876,  0.05285804,  0.02732605,
         0.03000097,  0.03023191, -0.00259226, -0.02139531,  0.03620126],
       [-0.05637009, -0.04464164,  0.09295276, -0.01944183,  0.01494247,
         0.02342485, -0.02867429,  0.02545259

In [18]:
mbgd=MBGDregressor(batch_size=int(x_train.shape[0]/10),learning_rate=0.01,epochs=50)

In [19]:
mbgd.fit(x_train,y_train)

152.36752534701964 [  52.2313776   -69.74481486  357.87117268  247.26420497   17.42599861
  -26.32147475 -170.49412055  118.76698445  316.01945695  131.17350483]


In [20]:
y_pred=mbgd.predict(x_test)

In [21]:
r2_score(y_test,y_pred)

0.434914019982797

In [22]:
from sklearn.linear_model import SGDRegressor

In [29]:
reg=SGDRegressor(learning_rate='constant',eta0=0.1)

In [30]:
batch_size=35
for i in range(100):
    idx=random.sample(range(x_train.shape[0]),batch_size)
    reg.partial_fit(x_train[idx],y_train[idx]) #which will perfom the iteration only once and through loop we perform it 100 times

In [31]:
reg.coef_

array([  62.76824655,  -75.13837757,  339.2208352 ,  249.16772217,
          9.55107262,  -30.0430826 , -171.50209266,  124.42249067,
        304.18224548,  113.45106136])

In [32]:
reg.intercept_


array([126.31319665])

In [33]:
y_pred=reg.predict(x_test)

In [34]:
r2_score(y_test,y_pred)

0.3078417902854934