In [2]:
import numpy as np

In [3]:
np.random.random()

0.9530278156001296

In [4]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [8]:
np.random.uniform(1,10)

2.3208030173540175

In [10]:
np.random.uniform(1,100,10).reshape(2,5)

array([[67.37628351, 42.31317543, 56.31029302, 14.89830692, 20.61204742],
       [80.2737123 , 96.857896  , 32.02899364, 69.53993895, 87.76252608]])

In [14]:
np.random.randint(1,100,15).reshape(3,5)

array([[53, 81, 42, 83, 16],
       [65, 69, 26, 99, 88],
       [ 8, 27, 26, 23, 10]])

In [15]:
a=np.random.randint(1,10,6)

In [16]:
a

array([4, 8, 8, 5, 6, 4])

In [17]:
np.max(a)

8

In [18]:
np.min(a)

4

In [19]:
np.argmax(a)

1

In [20]:
a[np.argmax(a)]

8

In [21]:
np.argmin(a)

0

In [22]:
a[np.argmin(a)]

4

In [23]:
a[(a%2)!=0]=-1

In [24]:
a

array([ 4,  8,  8, -1,  6,  4])

In [27]:
a=np.random.randint(1,20,6)

In [28]:
a

array([ 8, 11, 15,  1,  2, 18])

In [31]:
b=np.where(a%2==1,-1,a)

In [32]:
a

array([ 8, 11, 15,  1,  2, 18])

In [33]:
b

array([ 8, -1, -1, -1,  2, 18])

In [34]:
a=np.random.randint(1,50,10)

In [35]:
a

array([14,  4,  1, 14,  7, 22,  7,  3, 13, 28])

In [37]:
a=np.sort(a)

In [38]:
a

array([ 1,  3,  4,  7,  7, 13, 14, 14, 22, 28])

In [39]:
np.percentile(a,25)

4.75

In [40]:
np.percentile(a,50)

10.0

In [41]:
np.percentile(a,99.8)

27.891999999999996